version: '3.0'

services:
  auth_api:
    container_name: auth_api
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3003:3003
    command: yarn run start:dev
    restart: always
  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: