name: CI
on: [push]
jobs:
    init:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: GitHub Action for Yarn
              uses: Borales/actions-yarn@v3
            - name: install modules
              run: yarn
            - name: build
              run: yarn build
            - name: format
              run: yarn format
            - name: lint code
              run: yarn run lint